[features]
seeds = false
skip-lint = false
[programs.localnet]
test_program = "AECpbyv5BG7f7Ez9A3ZfKtGQUwbaeGPJng4tNDpKcwuY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/arthurtavares/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
